        CPPFLAGS := -Iinclude

            dirs := lib programs
        programs := buildtool
#        libtype := static
    test_scripts := test-buildtool

buildtool_cfiles := buildtool.c

default: all

include makefiles/project-root.make
